US026 Created branding and template
Les-Champignons/lc-kainosjobs-front pull request #2
Opened 2024-12-16 15:01 UTC by dandabs

2024-12-16 16:21 UTC, dylanBkainos approved these changes

2024-12-17 09:52 UTC, lukemKainos requested changes

2024-12-17 09:52 UTC, lukemKainos commented on src/app.ts
> +    console.log("Application running");
this could be a log message instead

2024-12-17 09:52 UTC, lukemKainos commented on src/app.ts
> +app.use(session({ secret: 'SUPER_SECRET', cookie: { maxAge: 28800000 } }));
can we make max age configurable?

2024-12-17 09:52 UTC, lukemKainos commented on views/index.njk
> +    <li>update job roles</li>
indent one more

2024-12-17 10:00 UTC, lukemKainos approved these changes

2024-12-17 10:01 UTC, dylanBkainos approved these changes

2024-12-17 10:02 UTC, merged