US040 Login system
Les-Champignons/lc-kainosjobs-front pull request #4
Opened 2024-12-17 13:57 UTC by dandabs

2024-12-18 12:46 UTC, lukemKainos requested changes

2024-12-18 12:46 UTC, lukemKainos commented on src/app.ts
> +  'node_modules/hmrc-frontend',
sorry who?

2024-12-18 12:46 UTC, lukemKainos commented on src/models/LoginRequest.ts
> +    password: String
trailing commas all through this pr please https://www.typescriptlang.org/docs/handbook/enums.html

2024-12-18 12:46 UTC, lukemKainos commented on src/models/User.ts
> +    email: String;
semi colon?

2024-12-18 12:46 UTC, lukemKainos commented on src/controllers/AuthController.ts
> +    req.session.token = null;
perhaps req.session.destroy().

2024-12-20 09:58 UTC, dandabs commented on src/models/User.ts
> +    email: String;
yes

2025-01-07 11:04 UTC, lukemKainos requested changes

2025-01-07 11:04 UTC, lukemKainos commented on views/auth/login.njk
> +
can we pop this in a fieldset with legend/aria?

2025-01-07 12:40 UTC, dandabs commented on views/auth/login.njk
> +
yes

2025-01-07 13:15 UTC, dylanmckk commented on package.json
> +		"test": "echo \"Error: no test specified\" && exit 1"
👀

2025-01-08 09:32 UTC, lukemKainos approved these changes

2025-01-08 09:42 UTC, dylanBkainos approved these changes

2025-01-08 09:42 UTC, merged

2025-01-09 09:39 UTC, dandabs commented
reopening this pr