US001 View Job Roles
Les-Champignons/lc-kainosjobs-front pull request #5
Opened 2024-12-18 15:44 UTC by CharlotteMKainos

2024-12-20 09:33 UTC, lukemKainos requested changes

2024-12-20 09:33 UTC, lukemKainos commented on src/controllers/JobRoleController.ts
> +		const jobRoles = await getAllJobRoles();
type this pls

2024-12-20 09:33 UTC, lukemKainos commented on test/unit/services/JobRoleServiceTests.ts
> +};
are these not the same?

2024-12-20 09:33 UTC, lukemKainos commented on test/unit/services/JobRoleServiceTests.ts
> +			}
do we need a try catch here?

2025-01-07 10:34 UTC, CharlotteMKainos commented on src/controllers/JobRoleController.ts
> +		const jobRoles = await getAllJobRoles();
this has been assigned type array

2025-01-07 10:35 UTC, CharlotteMKainos commented on test/unit/services/JobRoleServiceTests.ts
> +};
I saved the data and passed that in to reduce redundancy

2025-01-07 10:35 UTC, CharlotteMKainos commented on test/unit/services/JobRoleServiceTests.ts
> +			}
yes?

2025-01-07 11:07 UTC, lukemKainos commented on test/unit/services/JobRoleServiceTests.ts
> +			}
i mean as its in a test, why is an error message needed, if you do expect and it fails we want the test to fail, we dont need to catch it

2025-01-07 11:46 UTC, closed without merging